---
title: "Assignments"
---

<p style="color: #ba5e00">

Assigned readings and labs will be posted to this page on a weekly basis.

</p>

## Week 1

### Slides:

-   Lecture 1: [Course Welcome and Intro](https://docs.google.com/presentation/d/19t56kmk_K23At31wD8-u_MRKOtari-qHw5b3KCD4ReU/edit?usp=sharing)
-   Lecture 2: [Linear regression I](https://github.com/MaRo406/eds-232-machine-learning/blob/main/slides/Week1_slides_Regression%20I%20.pdf)

### Assigned Reading:

-   [HOML Ch. 1 (1.1 - 1.4)](https://bradleyboehmke.github.io/HOML/intro.html)

### Supplementary Reading:

-   [Statistical Modeling: The Two Cultures](https://projecteuclid.org/journals/statistical-science/volume-16/issue-3/Statistical-Modeling--The-Two-Cultures-with-comments-and-a/10.1214/ss/1009213726.full)

### Lab:

-   [Link to .Rmd](https://github.com/MaRo406/eds-232-machine-learning/blob/main/Lab1.Rmd)

## Week 2

### Slides:

-   Lecture 1: [Linear Regression II](https://github.com/MaRo406/eds-232-machine-learning/blob/main/docs/slides/Week2_slides_Regression%20II.pdf)

### Assigned Reading:

-   [HOML Ch. 2 (4.2-4.5)](https://bradleyboehmke.github.io/HOML/linear-regression.html#simple-linear-regression)
    -   Review of basic regression. Feel free to skim this a bit if you feel good about your understanding of linear regression.
-   [Tidy Models in R Ch. 3 (3.3-3.5)](https://www.tmwr.org/base-r.html#tidiness-modeling)
    -   Intro to Tidy Modeling. Provides some context for Lab 1 and beyond.

### Lab:

-   [Link to .Rmd](https://github.com/MaRo406/eds-232-machine-learning/blob/main/Lab2.Rmd)

## Week 3

### Slides:

-   Lecture 1: [Model Process and Regularized Regression](https://ucsb.box.com/s/qepqy1ndet8x51ym6rrv51y09k6qbug1)

### Assigned Reading:

-   [HOML Ch. 6](https://bradleyboehmke.github.io/HOML/regularized-regression.html)

### Supplementary Reading:

-   [Bias-Variance Scrollytelling](https://mlu-explain.github.io/bias-variance/)
-   [Gagne et al. (2018)](https://ucsb.box.com/s/w92iwiyspdjnuoam4yjzvkzbg6qi0t4q)

### Lab:

-   [Link to the Lab 3 Demo](https://github.com/MaRo406/eds-232-machine-learning/blob/main/Lab3_Demo.Rmd)

-   [Link to the Lab 3 Assignment](https://github.com/MaRo406/eds-232-machine-learning/blob/main/Lab3.Rmd)

## Week 4

### Slides:

-   Lecture 1: [Classification and Logistic Regression](https://ucsb.box.com/s/k9vnorvgepeny78ulvku6tjqxrw8djkt)

### Assigned Reading:

-   [HOML Ch. 5](https://bradleyboehmke.github.io/HOML/logistic-regression.html)

### Supplementary Reading:

These will help you with Lab 4.

-   [HOML Ch. 2.6](https://bradleyboehmke.github.io/HOML/process.html#model-eval)

-   [Cansler et al. 2020: Fire Tree Mortality Database paper](https://www.nature.com/articles/s41597-020-0522-7)

### Lab:

-   [Link to the Lab 4 Demo](https://raw.githubusercontent.com/MaRo406/eds-232-machine-learning/44053f8cfa4392d0a10edad2b4b3c1df83e7106e/Lab4_Demo.Rmd)

<!-- \### Assignment materials and dates -->

<!-- | Assignment materials | Assigned | Due date | -->

<!-- |----------------------|----------|----------| -->

<!-- | Link                 |          |          | -->

<!-- ###  -->
